### ISSUE TITLE
Warning: key_exists

### ISSUE THREAD

**Issue by erikvanberkum** [ATM-Consulting/dolibarr_module_productbycompany#2]
Following warning is displayed:

Warning: key_exists() expects parameter 2 to be array, null given in /var/www/html/dolmod/htdocs/core/class/commonobject.class.php on line 7594

Got the warning on following url

/custom/productbycompany/card.php?action=create&origin_id=1343&type=product&fk_product=1343&backtopage=%2Fcustom%2Fproductbycompany%2Flist.php%3Forigin_id%3D1343%26type%3Dproduct

**Comment by atm-lena** [comment]
Hello, 
We fixed the bug
